apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-ingestor
  name: location-ingestor
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    service: location-ingestor
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-ingestor
  name: location-ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-ingestor
  template:
    metadata:
      labels:
        service: location-ingestor
    spec:
      containers:
      - image: luroh/location-ingestor:latest
        name: location-ingestor
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
